[build-system]
requires = ['setuptools', 'wheel']
build-backend = 'setuptools.build_meta'

[project]
name = 'notes-cli'
version = '0.1.0'
description = 'A simple CLI tool for managing notes.'
authors = [{name = 'Your Name', email = 'your.email@example.com'}]
license = {file = 'LICENSE.txt'}
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
]
dependencies = ['click']

[project.scripts]
notes-cli = 'notes.cli:main'
